### ISSUE TITLE
kokkos version: cmake error

### ISSUE THREAD

**Issue by olivier-snl** [UoB-HPC/miniBUDE#20]
Using cmake 2.12.2, cmake errors out with the following when attempting to build the kokkos version:

```
CMake Error at CMakeLists.txt:86 (target_link_libraries):
  The plain signature for target_link_libraries has already been used with
  the target "bude".  All uses of target_link_libraries with a target must be
  either all-keyword or all-plain.

  The uses of the plain signature are here:

   * CMakeLists.txt:76 (target_link_libraries)
```

It seems that when there are multiple target_link_libraries lines, they either both need to have a keyword or not.  In your file kokkos/CMakeLists.txt, there are lines that have the PUBLIC keyword and one that does not.  I changed as follows to get a successful build:

```
--- a/kokkos/CMakeLists.txt
+++ b/kokkos/CMakeLists.txt
@@ -73,7 +73,7 @@ if(DEFINED OLD_CMAKE_CXX_FLAGS) # restore if overwritten before, as required by
     set(CMAKE_CXX_FLAGS ${OLD_CMAKE_CXX_FLAGS})
 endif()
 
-target_link_libraries(bude Kokkos::kokkos)
+target_link_libraries(bude PUBLIC Kokkos::kokkos)
 
 if (${CMAKE_VERSION} VERSION_LESS "3.13.0")
     message(WARNING "target_link_options is only available in CMake >= 3.13.0, using fallback target_link_libraries, this may cause issues with some compilers")
```

This may not be the only possible solution, but it worked for me -- I am no cmake expert...  I can PR if you like.

**Comment by tom91136** [comment]
We've migrated to a unified driver with improved CMake support in the main branch now so this should be resolved. Please reopen if this is not the case, thanks!
