### ISSUE TITLE
SYCL version won't build for oneAPI

### ISSUE THREAD

**Issue by gqchen1** [UoB-HPC/miniBUDE#22]
It has compiling issue (see the below)
In file included from /opt/intel/oneapi/compiler/2021.3.0/linux/bin/../include/sycl/CL/sycl/detail/generic_type_traits.hpp:16:
/opt/intel/oneapi/compiler/2021.3.0/linux/bin/../include/sycl/CL/sycl/half_type.hpp:79:9: fatal error: cannot assign to non-static data member within const member function 'operator-'
    Buf ^= 0x8000;
    ~~~ ^
/opt/intel/oneapi/compiler/2021.3.0/linux/bin/../include/sycl/CL/sycl/half_type.hpp:78:19: note: member function 'sycl::detail::host_half_impl::half::operator-' is declared const here
  constexpr half &operator-() {
  ~~~~~~~~~~~~~~~~^~~~~~~~~~~
1 error generated.

Here is oneAPI version,
Intel(R) oneAPI DPC++/C++ Compiler 2021.3.0 (2021.3.0.20210619)

After changing c++ standard from c++11 to c++17,  (-std=c++11 => -std=c++17), now it can compile.

**Comment by tom91136** [comment]
Thanks for reporting this, we're working on a new release which has a unified CMake build system. I'll leave this open until then.

**Comment by tom91136** [comment]
main branch now uses the unified build system and has been tested with the latest oneAPI release, please reopen if the problem persists.
