### ISSUE TITLE
Problems to execute benchmark on Nvidia GPU

### ISSUE THREAD

**Issue by ruialves7** [UoB-HPC/miniBUDE#23]
Hi, 

I'm using the computecpp 2.0.0, ubuntu 20.04 and a GPU Nvidia 1070.

when i trying build your benchmark, the system return the following error:
ptxas fatal : Unresolved extern function '_Z4fabsf'

What could be wrong?

Regards, 

Rui

**Comment by tom91136** [comment]
Could you provide the build commands you've used?
I believe ComputeCpp's CUDA support is experimental and still lacks device libraries (i.e math functions) hence `fabs` is an unresolved symbol.

**Comment by tom91136** [comment]
Closing as ComputeCpp is EOL.
