### ISSUE TITLE
Problem to Run SYCL Part

### ISSUE THREAD

**Issue by ruialves7** [UoB-HPC/miniBUDE#26]
Hi, 

I'm sorry for disturb you, but i have tried run miniBude using sycl, but i got a error:

Available SYCL devices:
  0. Host Device(host)
  1. NVIDIA GeForce RTX 2080 Ti(gpu)
Device    : NVIDIA GeForce RTX 2080 Ti
	Type    : gpu
	Profile : FULL_PROFILE
	Version : OpenCL 3.0 CUDA
	Vendor  : NVIDIA Corporation
	Driver  : 510.73.05
Poses     : 65536
Iterations: 8
Ligands   : 26
Proteins  : 938
Deck      : ../data/bm1
WG        : 4 (use nd_range:true)
free(): invalid pointer
Aborted

I managed to identify the function -> clCreateProgramWithBinary

Can you help to overcome this problem ?

Rui

**Comment by tom91136** [comment]
The main branch now contains updated driver which make issues like this a bit easier to debug.
I'm closing this for now but feel free to reopen if you still need help.
