### ISSUE TITLE
[v2] CUDA version uses fast math, SYCL does not

### ISSUE THREAD

**Issue by illuhad** [UoB-HPC/miniBUDE#31]
At least the v2 version of miniBUDE (have not looked at the other one) uses `--use_fast_math` with CUDA, while not using `-ffast-math` with SYCL. This causes results to not be comparable between the two. Fast math significantly impacts performance for this app.

Note that this does not impact `icpx` which uses `-ffast-math` by default.

**Comment by tom91136** [comment]
v2 is now main, so this should be resolved via [40ccb57](https://github.com/UoB-HPC/miniBUDE/commit/40ccb57625dfe2d68bb0bd27ad2a45265916734c).
